version: '3'

services:
  # Database
  db:
    image: mysql:8.0
    volumes:
      - db_data:/SQL/timetool.sql
    restart: always
    environment:
      MYSQL_DATABASE: timetool
      MYSQL_USER: root
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - wpsite
  