version: '3'

services:
  web:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - ./src/main:/var/web/html/
    links:
      - db
    networks:
      - default
  db:
    image: mysql:8.0
    ports:
      - '3307:3307'
    environment:
      MYSQL_DATABASE: myDb
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./SQL/dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    restart: always
    networks:
      - default
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - db:db
    ports:
      - '8080:8080'
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
volumes:
  persistent:
  