version: "3.8"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: enabled
      MYSQL_DATABASE: timetool
      MYSQL_USER: user
      MYSQL_PASSWORD: mypw
  admin:
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      - PMA_ARBITRARY=1
  timetool:
    build: .
    container_name: timetool
    depends_on:
      - db
    restart: always
    volumes:
      - ./src/main/:/var/www/html/
    ports:
      - "8080:80"