version: '3.7'

services:
  app:
    image: php:7.3-apache
    ports:
      - 3000:3000
    working_dir: /src/main
    volumes:
      - ./:/main
    enviroment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: time
  mysql:
    image: mysql:8.0
    ports:
      - '3307:3307'
    environment:
      MYSQL_DATABASE: myDb
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
volumes:
  mysql-data:
  
