CREATE TABLE IF NOT EXISTS `timetool`.`employee` ( 
    `EMPLOYEE_ID` INT NOT NULL AUTO_INCREMENT ,
    `FIRSTNAME` VARCHAR(20) NOT NULL ,
    `LASTNAME` VARCHAR(20) NOT NULL ,
    `SHORTNAME` VARCHAR(4) NOT NULL ,
    `PASSWORD` VARCHAR(45) NOT NULL ,
    `ROLE` INT NOT NULL ,
    `CREATED` TIMESTAMP NOT NULL ,
    `UPDATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    PRIMARY KEY (`EMPLOYEE_ID`(4)), UNIQUE (`SHORTNAME`(4))) 
ENGINE = InnoDB;