name: Docker Image

on:
  push:
    branches: [ $default-branch ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set tag var
      id: vars
      run: echo ::set-output name=docker_tag::$(echo ${GITHUB_REF} | cut -d'/' -f3)-${GITHUB_SHA}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag TimeDock:$(date +%s)
      
    - name: Scan docker image
      uses: Azure/container-scan@v0
      with:
         severity-threshold: MEDIUM
         image: TimeDock:${{ steps.vars.outputs.docker_tag }}
